export const PAGE_NAMES = {
  MORE: 'More',
  PROFILE: 'My profile',
  NAME: 'Name',
  USERNAME: 'Username',
  LOCATION: 'Location',
  BIO: 'Bio',
  Setting: 'Setting',
  ACCOUNT: 'Account',
  DELETE_ACCOUNT: 'Delete account',
  PRIVACY: 'Privacy and security',
  BLOCKED: 'Blocked',
  VISIBILITY: 'Visibility',
  NOTIFICATIONS: 'Notifications',
  NOTIFICATION_EMAIL: 'Email notifications',
  NOTIFICATION_PUSH: 'Push notifications',
  HELP: 'Help center',
  FEEDBACK: 'Feedback',
  ABOUT: 'About X',
}
